#!/bin/bash
chmod u+x *
# Get commit message from me
read -p "Enter commit message: " message

# Add all files to git staging area
git add .

# Commit changes with custom message
git commit -m "$message"

# Push changes to origin
git push

