#!/bin/bash

# Set variables
key_name="school"
key_bits=4096
key_passphrase="betty"

# Generate RSA key pair with specified name, bits, and passphrase
ssh-keygen -t rsa -b $key_bits -f ~/.ssh/$key_name -N $key_passphrase
